<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
    <xacro:include filename="robot_macro.xacro" />
    <xacro:include filename="common_properties.xacro" />

    <xacro:property name="box_base_length" value="0.4"/>
    <xacro:property name="cylinder_link_length" value="1.0"/>
    <xacro:property name="cylinder_link_radius" value="0.1"/>
    <xacro:property name="sphere_link_radius" value="0.2"/>

    <xacro:property name="gripper_filename" value="gripper_base.dae"/>
    <xacro:property name="gripper_orientation" value="-1.57"/>
    <xacro:property name="gripper_scale" value="$3"/>

    <xacro:property name="offset_cylinder" value="0.5"/>
    <xacro:property name="offset_sphere" value="0.05"/>
    <link name="world"/>
    <!-- Base Link -->
    <xacro:box_link name="base" pos_z="${- box_base_length / 2}" /> 

    <!-- Link1 -->
    <xacro:cylinder_link name="link1" pos_z="${box_base_length}" />

    <!-- Sphere1-->
    <xacro:sphere_link name="sphere1" pos_z="0.0" />

    <!-- Link2-->
    <xacro:cylinder_link name="link2" pos_z="${offset_cylinder}" /> 

    <!-- Sphere2-->
    <xacro:sphere_link name="sphere2" pos_z="0.0" />

    <!-- Link3-->
    <xacro:cylinder_link name="link3" pos_z="${offset_cylinder}" /> 

    <!-- ================================= -->
    <!-- | KINEMATIC PROPERTIES - JOINTS | -->
    <!-- ================================= -->

    <!-- World_Base_Joint -->
    <xacro:fixed_joint name="base_to_world" parent="world" child="base" pos_z="${box_base_length}"/>

    <!-- Base_Link1_Joint REVOLUTE-->
    <xacro:revolute_joint name="base_link1_joint" parent="base" child="link1" axis="z" pos_z="0.0"/>

    <!-- Link1_sphere1_Joint REVOLUTE-->
    <xacro:revolute_joint name="link1_sphere1_joint" parent="link1" child="sphere1" axis="y" pos_z="${cylinder_link_length + offset_sphere}"/> 

    <!-- Sphere1_Link2_Joint FIXED-->
    <xacro:fixed_joint name="sphere1_link2_joint" parent="sphere1" child="link2" pos_z="${sphere_link_radius - offset_sphere}"/> 

    <!-- Link2_sphere2_Joint REVOLUTE-->
    <xacro:revolute_joint name="link2_sphere2_joint" parent="link2" child="sphere2" axis="y" pos_z="${cylinder_link_length + offset_sphere}"/> 

    <!-- Sphere2_Link3_Joint FIXED-->
    <xacro:fixed_joint name="sphere2_link3_joint" parent="sphere2" child="link3" pos_z="${sphere_link_radius - offset_sphere}"/>  


</robot>