function [x0,x0_dot] = x0x0dot(phi,phi_dot,psi,psi_dot,theta,theta_dot,xG1,xG2,xG3,xG_dot1,xG_dot2,xG_dot3)
%X0X0DOT
%    [X0,X0_DOT] = X0X0DOT(PHI,PHI_DOT,PSI,PSI_DOT,THETA,THETA_DOT,xG1,xG2,xG3,xG_dot1,xG_dot2,xG_dot3)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    11-Nov-2024 12:31:03

x0 = [xG1;xG2;xG3;phi;theta;psi];
if nargout > 1
    t2 = cos(phi);
    t3 = cos(theta);
    t4 = sin(phi);
    x0_dot = [xG_dot1;xG_dot2;xG_dot3;phi_dot-psi_dot.*sin(theta);t2.*theta_dot+psi_dot.*t3.*t4;-t4.*theta_dot+psi_dot.*t2.*t3];
end
end
